name: 'Setup Common Steps'
description: 'Checks out code and sets up caching for cargo.'

runs:
  using: 'composite'
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo target
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
