name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Common setup
        uses: ./.github/actions/setup
      - name: Set up rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Common setup
        uses: ./.github/actions/setup
      - name: Run rustfmt
        run: cargo fmt --verbose -- --check
      - name: Run clippy
        run: cargo clippy --verbose -- -D warnings

  audit:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
